apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: job1
  name: job1
  namespace: chander
  #src: https://kubernetes.io/docs/concepts/workloads/controllers/job/
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 3
  completions: 10
  parallelism: 3
  suspend: false
  template:
    metadata:
      labels:
        job-name: job1
    spec:
      restartPolicy: Never
      containers:
      - command: [ "perl", "-Mbignum=bpi", "-wle", "print bpi(2999)" ]
        image: perl
        imagePullPolicy: IfNotPresent
        name: job1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
