apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: job2
  name: job2
  namespace: chander
  #src: https://kubernetes.io/docs/concepts/workloads/controllers/job/  ## CronJob is superset
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 3
  completions: 1
  parallelism: 3
  suspend: false
  template:
    metadata:
      labels:
        job-name: job2
    spec:
      restartPolicy: Never
      containers:
      - command:
        - /bin/sh
        - -c
        - date; echo Job without Cronjob from K8s
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        name: job2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
