apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: chander-lb
data:
  config: | 
   address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 192.168.0.95-192.168.0.100
     - 192.168.0.101-192.168.0.125
