---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-chander-nfs-storage
  namespace: pv-demo
spec:
  storageClassName: chander-nfs-storage
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: host
    path: "/k8s_share/vol0"
  #mountOptions:
    #- nfsvers=4.2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1-chander-nfs-storage
  namespace: chander
  annotations:
    volume.beta.kubernetes.io/storage-class: "chander-nfs-storage"
spec:
  storageClassName: chander-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-deploy-test
  name: nfs-deploy-test
  namespace: chander
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nfs-deploy-test
  template:
    metadata:
      labels:
        app: nfs-deploy-test
    spec:
      containers:
      - image: gcr.io/google_containers/busybox:1.24
        imagePullPolicy: IfNotPresent
        name: busybox
        command: 
        - "/bin/sh"
        - "-c"
        - "touch /mnt/`date +%H%M%S`;ls -l /mnt; echo Success;sleep 15;"
        volumeMounts: 
        - mountPath: /mnt
          name: pod-pvc1-chander-nfs-storage
          readOnly: false
        name: busybox
      restartPolicy: Always
      volumes:
      - name: pod-pvc1-chander-nfs-storage
        persistentVolumeClaim:
          claimName: pvc1-chander-nfs-storage
