---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: chander-nfs-storage
#provisioner: 192.168.0.121:/k8s_share
provisioner: host/k8s_share
parameters:
  server: 192.168.0.121
  path: /k8s_share 
  readOnly: "false"
  #archiveOnDelete: "false"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
