apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-pod1
  namespace: pv-demo
spec:
  containers:
  - image: gcr.io/google_containers/busybox:1.24
    name: test-nfs-pod1
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-45k2x
      readOnly: false
    - mountPath: /mnt
      name: pod-pvc1-chander-nfs-storage
      readOnly: false
    command:
    - "/bin/sh"
    - "-c"
    - "ls -l  /mnt; mount | grep k8s && echo Success || echo Failed; touch /mnt/test_pod.`date` && echo Success || echo Failed;sleep 15; echo I love k8s && exit 0 || exit 1 "
    #- " touch /mnt/test_pod.`date` && echo Success || echo Failed"
    #- "sleep 15; echo I love k8s && exit 0 || exit 1 "
  restartPolicy: Always
  volumes: 
  - name: pod-pvc1-chander-nfs-storage
    persistentVolumeClaim:
      claimName: pvc1-chander-nfs-storage
  - name: kube-api-access-45k2x
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
