apiVersion: "v1"
kind: Pod
metadata:
  name: web2
  labels:
    name: web
    app: demo
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
    - name: python
      image: us-central1-docker.pkg.dev/playground-s-11-d874486f/myrepo/py-red-sql
      env:       
        - name: "REDIS_HOST"
          value: "localhost"
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP                    
