apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: chander
spec:
  containers:
  - image: nginx
    name: test-nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
       medium: Memory
