apiVersion: v1
kind: Pod
metadata:
  name: test-webserver
  namespace: chander
spec:
  containers:
  - name: test-nginx-hostpath
    image: nginx
    volumeMounts:
    - mountPath: /learningk8s
      name: mydir
    - mountPath: /var/local/aaa/1.txt
      name: myfile
  volumes:
  - name: mydir
    hostPath:
      # Ensure the file directory is created.
      path: /vagrant/data/learningk8s
      type: DirectoryOrCreate
  - name: myfile
    hostPath:
      path: /vagrant/customize/chander.service
      type: FileOrCreate
