---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: task-pv-volume
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 100Ki
 accessModes:
  - ReadWriteOnce
 hostPath:
   path: "/opt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-first-app
  namespace: chander
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
     storage: 30Ki
---
