apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-mapped-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/ssd/host-mapped"
