apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pv-demo
  name: host-mapped-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
