apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  # storageClassName: chander-nfs
  mountOptions:
    - hard
    # - nfsvers=4.1
  nfs:
    path: /k8s_share/vol2
    server: 192.168.0.121
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  # storageClassName: chander-nfs
  mountOptions:
    - hard
    # - nfsvers=4.1
  nfs:
    path: /k8s_share/vol1
    server: 192.168.0.121
