apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  labels:
    label-one: "value-one"
  name: sqldatabase-sample
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: sqldatabase-dep
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: sqlinstance-sample-postgreshighavailability
spec:
  databaseVersion: POSTGRES_9_6
  region: us-central1
  settings:
    tier: db-custom-1-3840
    availabilityType: ZONAL
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: sqluser-sample
spec:
  instanceRef:
    name: sqluser-dep
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: sqluser-dep
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: sqluser-dep
data:
  password: cGFzc3dvcmQ=
---
