apiVersion: v1 
kind: Secret 
metadata:
  name: my-secret 
type: Opaque 
data:  
    secretkey1: c2VjcmV0    ## echo -n 'secret' | base64 
    secretkey2: YW5vdGhlcnNlY3JldA==   ## echo -n 'anothersecret' | base64