apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-direct-pv
spec:
  storageClassName: nfs-direct
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /ssd/direct
    server: 192.168.2.30

