apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 300Ki
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  # storageClassName: chander-nfs
  mountOptions:
    - hard
    # - nfsvers=4.1
  nfs:
    path: /k8s_share/vol2
    server: 192.168.0.121
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: chander
spec:
  resources:
    requests:
      storage: 100Ki
  # storageClassName: chander-nfs
  # selector:
  #  matchLabels:
  #    release: "stable"
  #  matchExpressions:
  #  - {key: environment, operator: In, values: [dev]}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
