apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: us-central1-docker.pkg.dev/playground-s-11-1d8eae57/myrepo/job-wq-2
      restartPolicy: OnFailure
