# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.provision :shell, privileged: true, inline: $install_common_tools

  %w{jnode3 jnode4 jnode5}.each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i + 1}"
        vb.memory = 2048
        vb.cpus = 1
      end
      #node.vm.box = "ubuntu/xenial64"
      node.vm.box = "bento/ubuntu-16.04"
      node.disksize.size = "65GB"
      node.vm.hostname = name
      node.vm.network "public_network", ip: "192.168.0.#{i + 26}"
      #node.vm.synced_folder "~/ansible", "/home/vagrant/ansible"
      node.vm.provision :shell, privileged: false, inline: <<-SHELL
#sudo /vagrant/join.sh
sudo kubeadm join 192.168.0.20:6443 --token ibzk37.dbf33oz3aln0js6w --discovery-token-ca-cert-hash sha256:71c5dca124a8b6925347e7ee609decb8b1932468ee2db7a7c5fba1f0b9fa7200
echo 'Environment="KUBELET_EXTRA_ARGS=--node-ip=192.168.0.#{i + 26}"' | sudo tee -a /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
echo " ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3K78sI/ZE/FYOGl4SOvfDD7eV1Um8gBEc8bFoR+Oeusee7mbYMDnSS9xOJIWzUYDgNcUlRMCdUOzh9J4nhg6xU6f6Pp4f6pC1wUdMG95TTocWJNfjN14lruBkyf8dI8YqopBpnhWQuD+CePSzHMV/CIa6lvGWQfIrvivANJ9EAAE+IYJ2VEawqEpvRI3KFan2Cg31BM/Tm6WnjiAaFlaDJLjudotuB40Y1Ffiy5Bnr+kyzbSIUtBOCdgY08nhjbgaEx6pSWD4LdbyXTOy9LtEv4xGC1c+3d2KvEgRZP9kXjiuuU47mswTjVbsjnLULv7n1tN7/LwcF7UD/2d/pLc9 cpbatth@cbatth \
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDN5T9l2eNUcuH94SGAvMPwC5GNw8cjMWkrMGeq+mUk6kcbVZlyUQ2sETnEHJCtdhFzF37FR85eOTM3q05TZdiEVt5vWyXe5AEFUCp+7cCp/XXAwLK4tcsVLM8kEq+OrREckvDM/D2qCdmCWb8su85CzhHKPLKSWBUl/TOmPjEfqXUiooM0H1eR61o8lGMPPpOOnUr8kAHDG/3ai4Y1DFbTZf5lrxy3KRVgUBUEwH+LZG61HTYzqjLmfoR8QPm6mqtijLmcmeyUl3VGNvzrSZDhdI/ZtAbwrDsLIVSEbAWR+cOY+VUhO9QDKue1yVPmACHvMINCuoP6vLmqdBPwa4tUnGewDmBEm3JiG2rqpd6vsxSG9yEIx6T21haibVCwcypm2/gEfD9pCqsRAVyu3SROHzlqqTU61ZmOCleoEnGd9kFWx95I234CKf0YfhMvt2g00DFYwZsN41HRS5bPKZ4vEs7XDph7Ua92oE0Sw/OJ1VRtek0Asa+riZfeEfvURY8= cbatth@pyflaskzoro2 " >> /home/vagrant/.ssh/authorized_keys
sudo systemctl daemon-reload
sudo systemctl restart kubelet
SHELL
    end
  end

  config.vm.provision "shell", inline: $install_multicast
end

$install_common_tools = <<-SCRIPT
# bridged traffic to iptables is enabled for kube-router.
cat >> /etc/ufw/sysctl.conf <<EOF
net/bridge/bridge-nf-call-ip6tables = 1
net/bridge/bridge-nf-call-iptables = 1
net/bridge/bridge-nf-call-arptables = 1
EOF

#
ip route change default via 192.168.0.1
#
set -e
IFNAME=$1
ADDRESS="$(ip -4 addr show $IFNAME | grep "inet" | head -1 |awk '{print $2}' | cut -d/ -f1)"
sed -e "s/^.*${HOSTNAME}.*/${ADDRESS} ${HOSTNAME} ${HOSTNAME}.local/" -i /etc/hosts

# remove ubuntu-bionic entry
sed -e '/^.*ubuntu-bionic.*/d' -i /etc/hosts
sed -e '/^.*ubuntu-xenial.*/d' -i /etc/hosts

# Patch OS
apt-get update && apt-get upgrade -y

# Create local host entries
echo "192.168.0.20 master" >> /etc/hosts
echo "192.168.0.21 node1" >> /etc/hosts
echo "192.168.0.22 node2" >> /etc/hosts
echo "192.168.0.23 node3" >> /etc/hosts

# disable swap
swapoff -a
sed -i '/swap/d' /etc/fstab

# Install kubeadm, kubectl and kubelet
export DEBIAN_FRONTEND=noninteractive
apt-get -qq install ebtables ethtool
apt-get -qq install jq xmlstarlet tmux git net-tools
apt-get -qq update
apt-get -qq install -y docker.io apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get -qq update
apt-get -qq install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubectl kubeadm

# Set external DNS
sed -i -e 's/#DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf
service systemd-resolved restart
SCRIPT

$install_multicast = <<-SHELL
apt-get -qq install -y avahi-daemon libnss-mdns
SHELL
