apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: config-vol
      mountPath: /etc/nginx
    - name: htpasswd-vol  
      mountPath: /etc/nginx/config            
  volumes:
  - name: config-vol
    configMap:
      name: nginx-config
  - name: htpasswd-vol
    secret:
      secretName: nginx-htpasswd
      
